package com.year2.queryme.service;

import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Component
public class SqlDialectAdapter {

    private static final Pattern MYSQL_LIMIT_OFFSET_PATTERN = Pattern.compile("(?i)\\bLIMIT\\s+(\\d+)\\s*,\\s*(\\d+)\\b");
    private static final Pattern IFNULL_PATTERN = Pattern.compile("(?i)\\bIFNULL\\s*\\(");
    private static final Pattern AUTO_INCREMENT_PATTERN = Pattern.compile("(?i)\\bAUTO_INCREMENT\\b");
    private static final Pattern UNSIGNED_PATTERN = Pattern.compile("(?i)\\bUNSIGNED\\b");
    private static final Pattern ENGINE_PATTERN = Pattern.compile("(?i)\\)\\s*ENGINE\\s*=\\s*[A-Za-z0-9_]+\\b");
    private static final Pattern RETURNING_PATTERN = Pattern.compile("(?i)\\bRETURNING\\b");
    private static final Pattern DML_PATTERN = Pattern.compile("^(INSERT|UPDATE|DELETE)\\b", Pattern.CASE_INSENSITIVE);

    public String adaptForExecution(String sql) {
        if (sql == null) {
            return null;
        }

        String adapted = replaceBacktickIdentifiers(sql);
        adapted = MYSQL_LIMIT_OFFSET_PATTERN.matcher(adapted).replaceAll("LIMIT $2 OFFSET $1");
        adapted = IFNULL_PATTERN.matcher(adapted).replaceAll("COALESCE(");
        adapted = AUTO_INCREMENT_PATTERN.matcher(adapted).replaceAll("GENERATED BY DEFAULT AS IDENTITY");
        adapted = UNSIGNED_PATTERN.matcher(adapted).replaceAll("");

        Matcher engineMatcher = ENGINE_PATTERN.matcher(adapted);
        StringBuffer engineBuffer = new StringBuffer();
        while (engineMatcher.find()) {
            engineMatcher.appendReplacement(engineBuffer, ")");
        }
        engineMatcher.appendTail(engineBuffer);

        return engineBuffer.toString();
    }

    public String ensureFinalStatementReturnsRows(String sql) {
        if (sql == null || sql.isBlank()) {
            return sql;
        }

        List<String> statements = SqlScriptUtils.splitStatements(sql);
        if (statements.isEmpty()) {
            return sql;
        }

        int lastIndex = statements.size() - 1;
        String lastStatement = statements.get(lastIndex).trim();
        String masked = SqlScriptUtils.maskSingleQuotedLiterals(lastStatement).trim();

        if (DML_PATTERN.matcher(masked.toUpperCase(Locale.ROOT)).find() && !RETURNING_PATTERN.matcher(masked).find()) {
            statements.set(lastIndex, lastStatement + " RETURNING *");
        }

        return String.join(";\n", statements);
    }

    private String replaceBacktickIdentifiers(String sql) {
        StringBuilder result = new StringBuilder(sql.length());
        boolean inSingleQuote = false;
        boolean inDoubleQuote = false;

        for (int i = 0; i < sql.length(); i++) {
            char ch = sql.charAt(i);

            if (ch == '\'' && !inDoubleQuote) {
                result.append(ch);
                if (inSingleQuote && i + 1 < sql.length() && sql.charAt(i + 1) == '\'') {
                    result.append(sql.charAt(++i));
                    continue;
                }
                inSingleQuote = !inSingleQuote;
                continue;
            }

            if (ch == '"' && !inSingleQuote) {
                result.append(ch);
                if (inDoubleQuote && i + 1 < sql.length() && sql.charAt(i + 1) == '"') {
                    result.append(sql.charAt(++i));
                    continue;
                }
                inDoubleQuote = !inDoubleQuote;
                continue;
            }

            if (ch == '`' && !inSingleQuote && !inDoubleQuote) {
                result.append('"');
                continue;
            }

            result.append(ch);
        }

        return result.toString();
    }
}
